# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-FakeRequest
version:      0.03
version_from: lib/Apache2/FakeRequest.pm
installdirs:  site
requires:
    Apache2::Request:              2.07

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
